### ISSUE TITLE
rk3568应该怎么玩，谢谢

### ISSUE THREAD

**Issue by ruoshui9527** [leafqycc/rknn-multi-threaded#13]
# 请切换到root用户

# CPU定频
echo "CPU0-3 可用频率:"
sudo cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_frequencies
sudo echo userspace > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
sudo echo 1992000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_setspeed
echo "CPU0-3 当前频率:"
sudo cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq

# NPU定频
echo "NPU 可用频率:"
sudo cat /sys/class/devfreq/fde40000.npu/available_frequencies
sudo echo userspace > /sys/class/devfreq/fde40000.npu/governor
sudo echo 900000000 > /sys/class/devfreq/fde40000.npu/userspace/set_freq
echo "NPU 当前频率:"
sudo cat /sys/class/devfreq/fde40000.npu/cur_freq
参照3588的定频脚本，对3568做了以上修改，帧率无变化。
貌似3568不支持多核，在rknnpool.py文件中都修改成了RKNNLite.NPU_CORE_AUTO
现在RKNNLite 为1.6版本，ubuntu20，

**Comment by leafqycc** [comment]
> # 请切换到root用户
> # CPU定频
> echo "CPU0-3 可用频率:" sudo cat /sys/devices/system/cpu/cpufreq/policy0/scaling_available_frequencies sudo echo userspace > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor sudo echo 1992000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_setspeed echo "CPU0-3 当前频率:" sudo cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq
> 
> # NPU定频
> echo "NPU 可用频率:" sudo cat /sys/class/devfreq/fde40000.npu/available_frequencies sudo echo userspace > /sys/class/devfreq/fde40000.npu/governor sudo echo 900000000 > /sys/class/devfreq/fde40000.npu/userspace/set_freq echo "NPU 当前频率:" sudo cat /sys/class/devfreq/fde40000.npu/cur_freq 参照3588的定频脚本，对3568做了以上修改，帧率无变化。 貌似3568不支持多核，在rknnpool.py文件中都修改成了RKNNLite.NPU_CORE_AUTO 现在RKNNLite 为1.6版本，ubuntu20，

此仓库版本为1.4.0，如果改成1.6.0应该有不少api需要修改，如果版本对应的话倒是仅需要修改少许部分，可以参考当时1.5.0版本的rk3568运行示例https://github.com/leafqycc/rknn-cpp-Multithreading/issues/18
3568的NPU只有单核，之前拿rk3566来测试过性能提升并不是很明显（大概是12->18 fps）

**Comment by ruoshui9527** [comment]
好的，我试试，谢谢
