### ISSUE TITLE
from rknnpool import rknnPoolExecutor

### ISSUE THREAD

**Issue by analwang** [leafqycc/rknn-multi-threaded#4]
想问一下为什么不是from rknnlite.api import RKNNLite or from rknn.api import RKNN像这样的?还是这意味它包含它们?
还有rknpu和rknnlite之间是什么关系?希望得到你的答案xiexie

**Comment by leafqycc** [comment]
> 想问一下为什么不是from rknnlite.api import RKNNLite or from rknn.api import RKNN像这样的?还是这意味它包含它们? 还有rknpu和rknnlite之间是什么关系?希望得到你的答案xiexie

包含关系，rknnpool是指rknnpool.py文件，我使用线程池ThreadPoolExecutor对rknn模型进行池化，并以此构建rknnPoolExecutor类,以降低rknn模型在多线程下频繁初始化的资源开销

**Comment by leafqycc** [comment]
> 想问一下为什么不是from rknnlite.api import RKNNLite or from rknn.api import RKNN像这样的?还是这意味它包含它们? 还有rknpu和rknnlite之间是什么关系?希望得到你的答案xiexie

简单来看的话，rknn框架的c++库是rknpu， python库是rknnlite，二者本质上是一样的，只有性能等略微的区别
